spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/factory-redis
      database: factory-redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000


server:
  port: 8080

cache:
  type: redis